# Generated by Django 4.1.4 on 2023-01-01 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_message_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='location',
            new_name='street',
        ),
        migrations.AddField(
            model_name='contact',
            name='city',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='country',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
